# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Europinion NOW
email: contact@studioalloy.nl
subtitle: Europinion Now, let us define the future of Europe!
description: > # this means to ignore newlines until "baseurl:"
  The European Union recently turned 70. Instead of great celebration, the current system is being disputed from all sides. Now is the time to to define the future of our Europe. Europinion NOW!
baseurl: "http://europinion-now.com" # the subpath of your site, e.g. /blog
url: "http://europinion-now.com" # the base hostname & protocol for your site
twitter_username: studioalloy
github_username:  studioalloy

image: image.jpg

# Build settings
markdown: kramdown

# Collections
collections:
  sections:
    output: true
